"""Default built-in application templates for RoostOS offline and initial setup."""

from typing import List, Dict, Any

DEFAULT_BUILTIN_APPS: List[Dict[str, Any]] = [
    {
        "id": "homeassistant",
        "name": "Home Assistant",
        "version": "2026.10.1",
        "category": "automation",
        "description": "Open source home automation that puts local control and privacy first.",
        "icon": "homeassistant",
        "author": "Home Assistant Community",
        "homepage": "https://www.home-assistant.io",
        "architectures": ["amd64", "arm64"],
        "recommended_role": "compute",
        "requested_scopes": ["devices:read", "network:read"],
        "container": {
            "image": "homeassistant/home-assistant:stable",
            "pull_policy": "if_not_present",
            "network_mode": "bridge",
            "ports": [{"host_port": 8123, "container_port": 8123, "protocol": "tcp"}],
            "volumes": [{"host_path": "/var/lib/roostos/apps/homeassistant", "container_path": "/config", "mode": "rw"}],
            "environment": {"TZ": "UTC"},
        },
        "ingress_preset": {"target_port": 8123, "suggested_subdomain": "ha", "ssl_required": True},
    },
    {
        "id": "immich",
        "name": "Immich",
        "version": "1.118.0",
        "category": "media",
        "description": "High performance self-hosted photo and video management solution.",
        "icon": "immich",
        "author": "Immich Authors",
        "homepage": "https://immich.app",
        "architectures": ["amd64", "arm64"],
        "recommended_role": "compute",
        "requested_scopes": [],
        "container": {
            "image": "ghcr.io/imagegenius/immich:latest",
            "pull_policy": "if_not_present",
            "network_mode": "bridge",
            "ports": [{"host_port": 2283, "container_port": 2283, "protocol": "tcp"}],
            "volumes": [{"host_path": "/var/lib/roostos/apps/immich/upload", "container_path": "/usr/src/app/upload", "mode": "rw"}],
            "environment": {"DB_HOSTNAME": "localhost"},
        },
        "ingress_preset": {"target_port": 2283, "suggested_subdomain": "photos", "ssl_required": True},
    },
    {
        "id": "vaultwarden",
        "name": "Vaultwarden",
        "version": "1.32.0",
        "category": "privacy",
        "description": "Unofficial Bitwarden compatible server written in Rust for password sync.",
        "icon": "vaultwarden",
        "author": "Vaultwarden Community",
        "homepage": "https://github.com/dani-garcia/vaultwarden",
        "architectures": ["amd64", "arm64"],
        "recommended_role": "compute",
        "requested_scopes": [],
        "container": {
            "image": "vaultwarden/server:latest",
            "pull_policy": "if_not_present",
            "network_mode": "bridge",
            "ports": [{"host_port": 8080, "container_port": 80, "protocol": "tcp"}],
            "volumes": [{"host_path": "/var/lib/roostos/apps/vaultwarden", "container_path": "/data", "mode": "rw"}],
            "environment": {"SIGNUPS_ALLOWED": "true"},
        },
        "ingress_preset": {"target_port": 8080, "suggested_subdomain": "passwords", "ssl_required": True},
    },
    {
        "id": "technitium-dns",
        "name": "Technitium DNS Server",
        "version": "12.2.0",
        "category": "privacy",
        "description": "Secure, self-hosted DNS server for ad-blocking and local domain resolution.",
        "icon": "shield",
        "author": "Technitium Software",
        "homepage": "https://technitium.com/dns/",
        "architectures": ["amd64", "arm64"],
        "recommended_role": "gateway",
        "requested_scopes": ["dns:manage", "network:read"],
        "container": {
            "image": "technitium/dns-server:latest",
            "pull_policy": "if_not_present",
            "network_mode": "bridge",
            "ports": [
                {"host_port": 53, "container_port": 53, "protocol": "udp"},
                {"host_port": 53, "container_port": 53, "protocol": "tcp"},
                {"host_port": 5380, "container_port": 5380, "protocol": "tcp"},
            ],
            "volumes": [{"host_path": "/var/lib/roostos/apps/technitium", "container_path": "/etc/dns", "mode": "rw"}],
            "environment": {},
        },
        "ingress_preset": {"target_port": 5380, "suggested_subdomain": "dns", "ssl_required": True},
    },
]
