import os
import sys
import subprocess
from roostos_engine.subsystems.base import Subsystem

class SystemSettingsSubsystem(Subsystem):
    name = "system_settings"
    dependencies = []

    def _is_local_dns_active(self) -> bool:
        """Checks if local DNS resolver (e.g. Technitium or port 53 listener) is active."""
        if hasattr(self.config, "plugins") and any(
            getattr(p, "enabled", True) and "dnsServer" in getattr(p, "known_services", [])
            for p in self.config.plugins
        ):
            return True
        if getattr(getattr(self.config.system, "dns", None), "ad_blocking_enabled", False):
            return True
        if not self.mock and os.environ.get("ROOSTOS_MOCK", "0") != "1" and os.environ.get("ROOSTOS_ETC_DIR") is None:
            try:
                import socket
                s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                s.settimeout(0.05)
                res = s.connect_ex(("127.0.0.1", 53))
                s.close()
                if res == 0:
                    return True
            except Exception:
                pass
        return False

    def update(self) -> None:
        """Applies global system configuration (hostname, domain name, DNS nameservers)."""
        hostname = self.config.system.hostname
        domain = self.config.system.domain
        etc_dir = os.environ.get("ROOSTOS_ETC_DIR")

        # Prepare DNS resolv.conf content
        forwarders = getattr(getattr(self.config.system, "dns", None), "forwarders", [])
        if not forwarders:
            forwarders = ["1.1.1.1", "8.8.8.8"]
        resolv_lines = ["# Generated by RoostOS\n"]
        if domain:
            resolv_lines.append(f"search {domain}\n")
        if self._is_local_dns_active():
            resolv_lines.append("nameserver 127.0.0.1\n")
        for dns in forwarders:
            resolv_lines.append(f"nameserver {dns}\n")
        resolv_content = "".join(resolv_lines)

        if etc_dir:
            try:
                os.makedirs(etc_dir, exist_ok=True)
                hostname_path = os.path.join(etc_dir, "hostname")
                with open(hostname_path, "w") as f:
                    f.write(f"{hostname}\n")
                
                hosts_path = os.path.join(etc_dir, "hosts")
                hosts_lines = []
                if os.path.exists(hosts_path):
                    with open(hosts_path, "r") as f:
                        for line in f:
                            if line.strip().startswith("127.0.0.1"):
                                hosts_lines.append(f"127.0.0.1 localhost {hostname}\n")
                            else:
                                hosts_lines.append(line)
                else:
                    hosts_lines = [f"127.0.0.1 localhost {hostname}\n"]
                with open(hosts_path, "w") as f:
                    f.writelines(hosts_lines)

                resolv_path = os.path.join(etc_dir, "resolv.conf")
                with open(resolv_path, "w") as f:
                    f.write(resolv_content)
                print(f"Mock applied hostname and DNS to {etc_dir}")
            except Exception as e:
                print(f"Error applying mock configuration to {etc_dir}: {e}", file=sys.stderr)
        elif not self.mock and os.getuid() == 0:
            try:
                with open("/etc/hostname", "w") as f:
                    f.write(f"{hostname}\n")
                
                hosts_lines = []
                if os.path.exists("/etc/hosts"):
                    with open("/etc/hosts", "r") as f:
                        for line in f:
                            if line.strip().startswith("127.0.0.1"):
                                hosts_lines.append(f"127.0.0.1 localhost {hostname}\n")
                            else:
                                hosts_lines.append(line)
                else:
                    hosts_lines = [f"127.0.0.1 localhost {hostname}\n"]
                with open("/etc/hosts", "w") as f:
                    f.writelines(hosts_lines)

                resolv_path = "/etc/resolv.conf"
                if os.path.islink(resolv_path):
                    is_resolved = False
                    try:
                        res = subprocess.run(["systemctl", "is-active", "--quiet", "systemd-resolved"], check=False)
                        is_resolved = (res.returncode == 0)
                    except Exception:
                        pass
                    if not is_resolved or not os.path.exists(resolv_path):
                        os.unlink(resolv_path)
                with open(resolv_path, "w") as f:
                    f.write(resolv_content)

                subprocess.run(["hostnamectl", "set-hostname", hostname], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
                print(f"Successfully applied hostname '{hostname}' and DNS to system")
            except Exception as e:
                print(f"Error applying system configuration: {e}", file=sys.stderr)
        else:
            print(f"Non-root or mock mode. Mock applied hostname: '{hostname}'")

        print(f"Applied local domain name: '{domain}'")
